<li class="link chatsystem wishlist" data-bind="scope: 'chatsystem'">
    <a <?= $block->getLinkAttributes() ?>><?= $block->escapeHtml($block->getLabel()) ?>
        <span
            data-bind="text: chatsystem().amount"
            class="counter amount">
        </span>
    </a>
</li>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "chatsystem": {
                        "component": "Lofmp_ChatSystem/js/view/chatsystem"
                    }
                }
            }
        }
    }
</script>
