<?php

use Lofmp\ChatSystem\Helper\Data;

$collection = $block->getTicket()
    ->setOrder('last_reply_at', 'desc');
$count = $collection->count();
$size = $collection->getSize();
$limit = $block->getLimit();
$currentPage = $block->getCurrentPage();
$start = $size - (($currentPage - 1) * $limit);
$modId = time() . rand();
$helper = $block->helper(Data::class);

?>
<?php if ($count) { ?>
    <div class="block lrw-block lrw-account-summary-listing">
        <div class="block-content">
            <div class="table-wrapper orders-recent">
                <table class="data-table table">
                    <thead>
                    <tr>
                        <th><?= $block->escapeHtml('ID'); ?></th>
                        <th><?= $block->escapeHtml('Subject'); ?></th>
                        <th><?= $block->escapeHtml('Category'); ?></th>
                        <th><?= $block->escapeHtml('Last Activity'); ?></th>
                        <th><?= $block->escapeHtml('Status'); ?></th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php $i = 0; ?>
                    <?php foreach ($collection as $_ticket) { ?>
                        <?php $amount = $_ticket->getAmount(); ?>
                        <tr class="<?= $block->escapeHtml($i % 2 ? 'odd' : 'even'); ?>
                        <?= ($i == $count - 1) ? 'last' : '' ?>">
                            <td><?= ($start - $i) ?></td>
                            <td>
                                <a class="box-body"
                                   href="<?= $block->escapeHtmlAttr($block->getUrl('lofmpchatsystem/ticket/view')); ?>">
                                    <?= $block->escapeHtmlAttr($_ticket->getSubject()); ?>
                                </a>
                            </td>
                            <td><?= $block->escapeHtmlAttr($block->getCategoryName($_ticket->getCategoryId())); ?>
                            </td>
                            <td><?= $block->escapeHtmlAttr($_ticket->getLastReplyAt()); ?></td>
                            <td class="lrw-status-<= str_replace("
                            ", "-", $block->escapeHtmlAttr(strtolower($block->getStatus($_ticket->getStatusId())))); ?>
                            ">
                            <?= $block->escapeHtmlAttr($block->getStatus($_ticket->getStatusId())); ?>
                            </td>
                            <td>
                                <?php if ($block->getUnreadMessageCount($_ticket->getData('ticket_id')) > 0) { ?><i
                                    class="fa fa-circle unread" aria-hidden="true"></i>
                                <?php } else { ?>
                                    <i class="fa fa-circle" aria-hidden="true"></i>
                                <?php } ?>
                            </td>
                        </tr>
                        <?php $i++; ?>
                    <?php } ?>
                    </tbody>
                </table>
            </div>
            <?= $block->getChildHtml('toolbar'); ?>
        </div>
    </div>

<?php } ?>
<div class="block lrw-block lrw-account-summary-listing">
    <div class="block-title">
        <strong><?= $block->escapeHtml('Create New Ticket'); ?></strong>
    </div>
    <div class="block-content">
        <div class="orders-recent">
            <div id="lofmpform<?= $block->escapeHtmlAttr($modId); ?>" class="chatsystem-form">
                <div class="form-content">
                    <form id="chatsystem<?= $block->escapeHtmlAttr($modId); ?>" class="chatsystem form"
                          action="<?= $block->escapeHtmlAttr($block->getUrl('*/*/saveticket')); ?>"
                          method="post"
                          data-hasrequired="<?= $block->escapeHtml('* Required Fields') ?>"
                          data-mage-init='{"validation":{}}'
                          enctype="multipart/form-data">
                        <div class="form-list row">
                            <div class="field col-sm-6">
                                <div class="response-field-text">
                                    <div class="subtemplate-wrapper" style="">
                                        <label for="subject" class="required"><?= $block->escapeHtml('Subject'); ?>
                                            <em>*</em>
                                        </label>
                                        <div class="row">
                                            <div class="col-sm-12">
                                                <div class="subtemplate-inner">
                                                    <input name="subject" id="subject" title="Subject" value=""
                                                           class="input-text required-entry _required" type="text">
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="field col-sm-3">
                                <div class="response-field-text">
                                    <div class="subtemplate-wrapper" style="">
                                        <label for="category_id"
                                               class="required"><?= $block->escapeHtmlAttr('Category'); ?>
                                            <em>*</em>
                                        </label>
                                        <div class="row">
                                            <div class="col-sm-12">
                                                <div class="subtemplate-inner">
                                                    <select id="category_id" name="category_id"
                                                            class="form-control select2 required-entry"
                                                            style="width: 100%;">
                                                        <option
                                                            value><?= $block->escapeHtml('Select a category'); ?>
                                                        </option>
                                                        <?php
                                                        foreach ($block->getCategory() as $key => $category) { ?>
                                                            <option
                                                                value="<?= $block
                                                                    ->escapeHtmlAttr($category
                                                                        ->getData('category_id')); ?>">
                                                                <?= $block
                                                                    ->escapeHtmlAttr($category
                                                                        ->getData('title')); ?>
                                                            </option>
                                                        <?php } ?>
                                                    </select>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="field col-sm-3">
                                <div class="response-field-text">
                                    <div class="subtemplate-wrapper" style="">
                                        <label
                                            for="priority_id"
                                            class="required"><?= $block->escapeHtml('Priority'); ?>
                                            <em>*</em>
                                        </label>
                                        <div class="row">
                                            <div class="col-sm-12">
                                                <div class="subtemplate-inner">
                                                    <select id="priority_id" name="priority_id"
                                                            class="form-control select2 required-entry"
                                                            style="width: 100%;">
                                                        <option
                                                            value><?= $block->escapeHtmlAttr('Select a priority'); ?>
                                                        </option>
                                                        <?php foreach ($block->getPriority() as $key => $priority) { ?>
                                                            <option
                                                                value="<?= $block->escapeHtmlAttr($priority['id']); ?>">
                                                                <?= $block->escapeHtmlAttr($priority['title']); ?>
                                                            </option>
                                                        <?php } ?>
                                                    </select>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="field col-sm-12">
                                <div class="response-field-text">
                                    <div class="subtemplate-wrapper" style="">
                                        <label
                                            for="description "
                                            class="required"><?= $block->escapeHtml('Message '); ?>
                                            <em>*</em>
                                        </label>
                                        <div class="row">
                                            <div class="col-sm-12">
                                                <div class="subtemplate-inner">
                                                    <textarea name="description" id="description"
                                                              class="input-text required-entry _required" rows="5"
                                                              aria-required="true"></textarea>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="field col-sm-12 ">
                                <div class="response-field-file_upload">
                                    <div class="subtemplate-wrapper" style="">
                                        <label for="attachment" style=""
                                               class="required"><?= $block->escapeHtml('Attachment'); ?>
                                        </label>
                                        <div class="input-box">
                                            <input name="attachment" id="attachment" style="" title="Attachment"
                                                   class="input-text " type="file">
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <?php if (count($block->getOrder()) > 0) { ?>
                                <div class="field col-sm-6">
                                    <div class="response-field-text">
                                        <div class="subtemplate-wrapper" style="">
                                            <label
                                                for="order_id"
                                                class="required"><?= $block->escapeHtml('Order'); ?>
                                            </label>
                                            <div class="row">
                                                <div class="col-sm-12">
                                                    <div class="subtemplate-inner">
                                                        <select id="order_id" name="order_id"
                                                                class="form-control select2">
                                                            <option>
                                                                <?= $block->escapeHtml('Select an order'); ?>
                                                            </option>
                                                            <?php foreach ($block->getOrder() as $key => $order) { ?>
                                                                <option
                                                                    value="<?= $block->escapeHtmlAttr($order['id']);?>">
                                                                    <?= $block->escapeHtmlAttr($order['name']); ?>
                                                                </option>
                                                            <?php } ?>
                                                        </select>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="field col-sm-6">
                                    <div class="response-field-text">
                                        <div class="subtemplate-wrapper" style="">
                                            <label
                                                for="product_id"
                                                class="required"><?= $block->escapeHtml('Product'); ?>
                                            </label>
                                            <div class="row">
                                                <div class="col-sm-12">
                                                    <div class="subtemplate-inner">
                                                        <select multiple id="product_id" name="products[]"
                                                                class="form-control multiple">

                                                        <?php foreach ($block->getProduct() as $key => $product) { ?>
                                                                <option
                                                                    value="<?= $block
                                                                        ->escapeHtmlAttr($product['value']); ?>">
                                                                    <?= $block->escapeHtmlAttr($product['label']); ?>
                                                                </option>
                                                            <?php } ?>
                                                        </select>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            <?php } ?>
                        </div>
                        <div class="row">
                            <div class="buttons-set col-sm-12">
                                <button type="submit" title="Submit" class="formbuilder-button button">
                                <span>
                                    <?= $block->escapeHtml('Submit Ticket'); ?>
                                </span>
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
