<?php

use Lofmp\ChatSystem\Helper\Data;

$ticket = $block->getTicket();
$block->isRead();
$message = $block->getMessage($ticket->getTicketId());
$modId = time() . rand();
$helper = $block->helper(Data::class);

?>
<div class="block lrw-block lrw-account-summary-listing">
    <div class="block-content">
        <div class="table-wrapper orders-recent">
            <table class="data-table table">
                <tbody>
                <tr>
                    <th><?= $block->escapeHtml('Department'); ?></th>
                    <td>
                        <?= $block->escapeHtmlAttr($helper->getDepartmentById($ticket->getDepartmentId())
                            ->getTitle()); ?>
                    </td>
                </tr>
                <tr>
                    <th><?= $block->escapeHtml('Priority'); ?></th>
                    <td><?= $block->escapeHtmlAttr($block->getPriority($ticket->getPriorityId())); ?></td>
                </tr>
                <tr>
                    <th><?= $block->escapeHtml('Category'); ?></th>
                    <td><?= $block->escapeHtmlAttr($block->getCategoryName($ticket->getCategoryId())); ?></td>
                </tr>
                <tr>
                    <th><?= $block->escapeHtml('Status'); ?></th>
                    <td><?= $block->escapeHtmlAttr($block->getStatus($ticket->getStatusId())); ?></td>
                </tr>
                <tr>
                    <th><?= $block->escapeHtml('Rating'); ?></th>
                    <td>
                        <div class="ratings">
                            <?php if ($ticket->getRating()) { ?>
                                <div class="rating-box">
                                    <div class="rating" style="width:<?= ($ticket->getRating() / 5 * 100); ?>%"></div>
                                </div>
                            <?php } else { ?>
                                <div id="rating_1" class="ratings">
                                    <div id="1" class="star_1  ratings_stars"></div>
                                    <div id="2" class="star_2  ratings_stars"></div>
                                    <div id="3" class="star_3  ratings_stars"></div>
                                    <div id="4" class="star_4 ratings_stars"></div>
                                    <div id="5" class="star_5 ratings_stars"></div>
                                    <input name="rating" id="total_votes" title="Rating" class="input-text"
                                           type="hidden" value="5">
                                </div>
                            <?php } ?>
                            <div class="check-rating">
                                <?php if (!$ticket->getRating()) {
                                    echo "Rating for ticket";
                                } ?>
                            </div>
                        </div>

                    </td>
                </tr>
                <tr>
                    <th><?= $block->escapeHtml('Order'); ?></th>
                    <td>
                        <?= $block->escapeHtmlAttr($block->getOrderTicket($ticket->getOrderId())); ?>
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>
<?php if ($ticket->getStatusId() != 0) { ?>
    <div class="block lrw-block lrw-account-summary-listing">
        <div class="block-title">
            <strong><?= $block->escapeHtml('Post Reply'); ?></strong>
        </div>
        <div class="block-content">
            <div class="orders-recent">
                <div id="lofmpform<?= $block->escapeHtmlAttr($modId); ?>" class="chatsystem-form">
                    <div class="form-content">
                        <form id="chatsystem<?= $block->escapeHtmlAttr($modId); ?>" class="chatsystem form"
                              action="<?= $block->escapeHtmlAttr($block->getUrl('*/*/savemessage')); ?>" method="post"
                              data-hasrequired="<?= $block->escapeHtml('* Required Fields') ?>"
                              data-mage-init='{"validation":{}}'
                              enctype="multipart/form-data">
                            <input type="hidden" name="ticket_id"
                                   value="<?= $block->escapeHtmlAttr($ticket->getData('ticket_id')); ?>"/>
                            <input type="hidden" name="category_id"
                                   value="<?= $block->escapeHtmlAttr($ticket->getData('category_id')); ?>"/>
                            <div class="form-list row">
                                <div class="field col-sm-12">
                                    <div class="response-field-text">
                                        <div class="subtemplate-wrapper" style="">
                                            <label for="body "
                                                   class="required">
                                                <?= $block->escapeHtmlAttr($block->escapeHtml('Message ')); ?>
                                                <em>*</em>
                                            </label>
                                            <div class="row">
                                                <div class="col-sm-12">
                                                    <div class="subtemplate-inner">
                                                        <textarea name="body" id="body"
                                                                  class="input-text required-entry _required" rows="5"
                                                                  aria-required="true"></textarea>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="field col-sm-12 ">
                                    <div class="response-field-file_upload">
                                        <div class="subtemplate-wrapper" style="">
                                            <label for="attachment" style=""
                                                   class="required"><?= $block->escapeHtml('Attachment'); ?>
                                            </label>
                                            <div class="input-box">
                                                <input name="attachment" id="attachment" style="" title="Attachment"
                                                       class="input-text " type="file">
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="buttons-set col-sm-12">
                                    <button type="submit" title="Submit" class="formbuilder-button button">
                                <span>
                                    <?= $block->escapeHtml('Post Reply'); ?>
                                </span>
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
<?php } ?>
<div class="block lrw-block lrw-account-summary-listing">
    <div class="block-title">
        <strong><?= $block->escapeHtml('History Ticket'); ?></strong>
    </div>
    <div class="block-content">
        <div class="orders-recent">
            <?php
            $data = '';
            $class = '';
            foreach ($message->setOrder('created_at', 'desc') as $key => $_message) {
                if ($_message->getData('user_name')) {
                    $name = $_message->getData('user_name');
                    $class = 'user';
                    $countlike = $block->getSumLike('user_id', $_message->getData('user_id'));
                } else {
                    $name = $_message->getData('customer_name');
                    $class = '';
                    $countlike = $block->getSumLike('customer_id', $_message->getData('customer_id'));
                }
                $data .= '<div class="lofmp-ticket-history">';
                $data .= '<div class="lofmp-message">';
                $data .= '<div class="lofmp-message-header">';
                $data .= '<strong>' . $name . '</strong>';
                $data .= '<span class="minor">' . __(
                    'added %1 (%2)',
                    $helper->nicetime($_message->getCreatedAt()),
                    $_message->getCreatedAt()
                ) . '</span>';
                $data .= '<span class="like">' .
                    '<i class="fa fa-thumbs-up like_id_'
                    . $_message->getMessageId() .
                    '" aria-hidden="true" data-countlike="'
                    . $countlike . '">' . $countlike . '</i></span>';
                $data .= '</div>';
                $data .= '<div class="lofmp-message-body ' . $class . '">';
                $data .= $_message->getBody();
                foreach ($block->getAttachment($_message->getMessageId()) as $key => $attachment) {
                    $data .= '<div class="lofmp-message-attachments">';
                    $data .= '<a href="' . $attachment->getImageUrl() . '">' . $attachment->getName() . '</a></div>';
                }

                $data .= '</div>';
                if ($_message->getData('user_name')) {
                    $data .= '<div class="comment-buttons">';
                    $data .= '<span class="like-button">';
                    $data .= '<a  class="like-comment button tiny" data-userid="' . $_message->getData('user_id')
                        . '" data-messageid="' . $_message->getData('message_id') . '">';
                    $data .= '<i class="fa fa-thumbs-up" aria-hidden="true"></i><span>' . __('Like') . '</span>';
                    $data .= '</a>';
                    $data .= '</span>';
                    $data .= '<div class="thank-like message_id_' . $_message->getMessageId() . '">';

                    $data .= '</div>';
                    $data .= '</div>';
                }
                $data .= '</div>';
                $data .= '</div>';
            }
            echo $block->escapeHtmlAttr($data);
            ?>
        </div>
    </div>
</div>
<script type="text/javascript">
    require([
            'jquery',
        ],
        function () {
            jQuery(document).ready(function ($) {
                $('.ratings_stars').mouseover(
                    function () {
                        $(this).prevAll().andSelf().addClass('ratings_over');
                        $(this).nextAll().removeClass('ratings_over');
                        var id = $(this).parent().attr("id");
                        var num = $(this).attr("id");
                        $('#total_votes').val(num);

                    });
                $('#rating_1 .ratings_stars').click(function () {
                    var self = $(this);
                    var rating = $('#total_votes').val();

                    $.ajax({
                        url: '<?= $block->escapeHtmlAttr($block->getUrl('lofmpchatsystem/rating/post')); ?>',
                        type: 'post',
                        data: {
                            rating: rating,
                            ticket_id: <?= $block->escapeHtmlAttr($ticket->getData('ticket_id')); ?>
                        },
                        dataType: 'json',
                        success: function (result) {

                            var rating = result.rating / 5 * 100;

                            $('.ratings .check-rating').html(result.message);
                            $('#rating_1.ratings').html('<div class="rating-box"><div class="rating" style="width:'
                                + rating + '%"></div></div>');
                        }
                    });
                    return false;
                });
                $('.lofmp_chatsystem').addClass('current');
                $('.like-button .like-comment').click(function () {
                    var userid = $(this).data('userid');
                    var messageid = $(this).data('messageid');
                    var countlike = $(this).closest('.lofmp-message').find('.fa-thumbs-up').data('countlike');
                    $.ajax({
                        url: '<?= $block->escapeHtmlAttr($block->getUrl('lofmpchatsystem/rating/like')); ?>',
                        type: 'post',
                        data: {userid: userid, messageid: messageid, countlike: countlike},
                        dataType: 'json',
                        success: function (result) {
                            $(result.like_id).html(result.like);
                            $(result.id).html(result.message);
                        }
                    });
                    return false;
                });
            });
        });
</script>
